### ISSUE TITLE
How to repeat previous command?

### ISSUE THREAD

**Issue by mindstormer12** [krikx/SublimeShell#1]
Using Sublime Text 3 on Windows with SublimeShell installed--the up arrow key does not show the previous command used. Does SublimeShell have this feature and if not, is it being considered? I was looking for a built-in shell for Sublime Text so can easily compile and test my code using command line arguments, which involves lots of repeating commands.

Also, I can't seem to clear the _Shell Output_ using the command CLS on Windows.

**Comment by avamsi** [comment]
Hi @mindstormer12 
I am not sure if Sublime exposes API for history in quick panel.
Take a look at [SublimeREPL](https://github.com/wuub/SublimeREPL). You can launch shell via command palette. It supports history.

Also, something like cls/clear or vim obviously won't work because we are not actually integrating a shell to Sublime. For that see [SublimePTY](https://github.com/wuub/SublimePTY).
